Repository openmc-dev/openmc, pull requests merged in 2019-09, with the labels that each got.

#1313 Use energy-dependent fission yields when constructing depletion matrix
  docs/source/pythonapi/deplete.rst
  openmc/deplete/_matrix_funcs.py
  openmc/deplete/abc.py
  openmc/deplete/chain.py
  openmc/deplete/cram.py
  openmc/deplete/helpers.py
  openmc/deplete/nuclide.py
  openmc/deplete/operator.py
  tests/dummy_operator.py
  tests/unit_tests/test_deplete_chain.py
  tests/unit_tests/test_deplete_fission_yields.py
  tests/unit_tests/test_deplete_nuclide.py
Labels: Depletion

#1322 Process non-fission heating from njoy
  openmc/data/neutron.py
  openmc/data/njoy.py
  openmc/data/reaction.py
  src/reaction.cpp
  tests/unit_tests/test_data_neutron.py
Labels: Data

#1331 Remove cram wrapper with maps of depletion matrices
  openmc/deplete/cram.py
Labels: Depletion

#1333 Bug fix for Material.add_nuclide with unrecognized nuclides
  openmc/data/data.py
  tests/unit_tests/test_pin.py
Labels: Bugs

#1341 Fission heating fixes - mark redundant, consistent energy grid
  openmc/data/neutron.py
Labels: Bugs

#1343 Use defaultdict when weighting fission yields
  openmc/deplete/abc.py
  openmc/deplete/chain.py
  openmc/deplete/helpers.py
  tests/dummy_operator.py
  tests/unit_tests/test_deplete_chain.py
Labels: Bugs, Depletion

#1350 Use MT301,901 for energy deposition for depletion
  docs/source/methods/energy_deposition.rst
  docs/source/methods/index.rst
  docs/source/pythonapi/deplete.rst
  docs/source/usersguide/tallies.rst
  openmc/deplete/dummy_comm.py
  openmc/deplete/helpers.py
  openmc/deplete/operator.py
  openmc/deplete/results_list.py
Labels: Depletion

#1332 Depletion example notebook
  docs/source/examples/index.rst
  docs/source/examples/pincell-depletion.rst
  docs/source/usersguide/depletion.rst
  examples/jupyter/pincell_depletion.ipynb
  examples/python/pincell_depletion/restart_depletion.py
  examples/python/pincell_depletion/run_depletion.py
  openmc/deplete/operator.py
Labels: Depletion, Documentation

#1353 Allow tests to run when OPENMC_ENDF_DATA is not set
  tests/unit_tests/test_data_decay.py
  tests/unit_tests/test_data_neutron.py
  tests/unit_tests/test_data_photon.py
  tests/unit_tests/test_data_thermal.py
  tests/unit_tests/test_deplete_chain.py
Labels: Test Suite

#1352 Cleaner depletion module documentation and namespace
  docs/source/_templates/mycallable.rst
  docs/source/pythonapi/deplete.rst
  openmc/deplete/__init__.py
  openmc/deplete/abc.py
  openmc/deplete/chain.py
  openmc/deplete/cram.py
  openmc/deplete/nuclide.py
  openmc/deplete/operator.py
  openmc/deplete/reaction_rates.py
  openmc/deplete/results.py
  openmc/deplete/results_list.py
Labels: Depletion, Documentation

#1355 Add discussion in user's guide on depletion caveats
  docs/source/usersguide/depletion.rst
Labels: Depletion, Documentation

#1356 Provide class-based depletion solvers
  docs/source/pythonapi/deplete.rst
  openmc/deplete/abc.py
  openmc/deplete/cram.py
Labels: Depletion
