Repository openmc-dev/openmc, pull requests merged in 2020-01, with the labels that each got.

#1464 Ensure a valid bin is picked for short tracks in tally meshes
  src/mesh.cpp
Labels: Bugs

#1452 Support pre-evaluated data in Chain.from_endf
  openmc/deplete/chain.py
Labels: Depletion

#1381 Lattice discretization with degenerate and recursive local neighbor symmetry algorithms
  openmc/cell.py
  openmc/geometry.py
  openmc/lattice.py
  openmc/universe.py
  tests/unit_tests/test_cell.py
  tests/unit_tests/test_lattice.py
  tests/unit_tests/test_lattice_discretization.py
  tests/unit_tests/test_universe.py
Labels: Geometry, MGXS
