Repository openmc-dev/openmc, pull requests merged in 2024-04, with the labels that each got.

#2859 changing y axis label for heating plots
  openmc/plotter.py
  tests/unit_tests/test_plotter.py
Labels: Plots

#2942 Ensure that two surfaces with different boundary type are not considered redundant
  openmc/geometry.py
  tests/unit_tests/test_geometry.py
Labels: Merging Soon

#2949 Support UnstructuredMesh for IndependentSource
  openmc/filter.py
  openmc/mesh.py
  openmc/source.py
  tests/unit_tests/test_mesh.py
  tests/unit_tests/test_source_mesh.py
Labels: Merging Soon

#2958 Update minimum Python version to 3.8
  .github/workflows/ci.yml
  docs/source/devguide/styleguide.rst
  docs/source/usersguide/install.rst
  setup.py
Labels: Merging Soon

#2823 Random Ray Transport
  CMakeLists.txt
  docs/source/_images/2x2_fsrs.jpeg
  docs/source/_images/2x2_materials.jpeg
  docs/source/io_formats/settings.rst
  docs/source/methods/index.rst
  docs/source/methods/random_ray.rst
  docs/source/usersguide/data.rst
  docs/source/usersguide/index.rst
  docs/source/usersguide/random_ray.rst
  examples/pincell_random_ray/build_xml.py
  include/openmc/boundary_condition.h
  include/openmc/cell.h
  include/openmc/constants.h
  include/openmc/mgxs.h
  include/openmc/output.h
  include/openmc/plot.h
  include/openmc/random_ray/flat_source_domain.h
  include/openmc/random_ray/random_ray.h
  include/openmc/random_ray/random_ray_simulation.h
  include/openmc/settings.h
  include/openmc/timer.h
  openmc/settings.py
  src/boundary_condition.cpp
  src/eigenvalue.cpp
  src/geometry.cpp
  src/main.cpp
  src/mesh.cpp
  src/output.cpp
  src/random_ray/flat_source_domain.cpp
  src/random_ray/random_ray.cpp
  src/random_ray/random_ray_simulation.cpp
  src/settings.cpp
  src/simulation.cpp
  src/source.cpp
  src/tallies/tally.cpp
  src/timer.cpp
  tests/regression_tests/random_ray_basic/__init__.py
  tests/regression_tests/random_ray_basic/inputs_true.dat
  tests/regression_tests/random_ray_basic/results_true.dat
  tests/regression_tests/random_ray_basic/test.py
  tests/regression_tests/random_ray_vacuum/__init__.py
  tests/regression_tests/random_ray_vacuum/inputs_true.dat
  tests/regression_tests/random_ray_vacuum/results_true.dat
  tests/regression_tests/random_ray_vacuum/test.py
  tests/testing_harness.py
  tests/unit_tests/test_settings.py
Labels: Random Ray

#2972 Update bounding_box docstrings
  openmc/cell.py
  openmc/region.py
Labels: Merging Soon
